[project]
name = "drawings"
version = "0.0.0"
description = "A creative outlet for fun and stuff."
requires-python = ">=3.11"
dynamic = ["dependencies", "optional-dependencies"]

[project.urls]
repository = "https://github.com/Bilbottom/drawings"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {file = ["requirements-dev.txt"]}


[tool.pytest.ini_options]
addopts = "--cov=drawings --cov-report term-missing --cov-fail-under=60"
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
